get http://localhost:3000/pets.json

###
post http://localhost:3000/pets.json
Content-Type: application/json

{
  "name": "Fido",
  "animal": "dog",
  "age": 9
}

###
patch http://localhost:3000/pets/4.json
Content-Type: application/json

{
  "name": "Billy",
  "animal": "dog",
  "age": 6
}

###
delete http://localhost:3000/pets/6.json